version: '3.8'
name: 'rpf'

services:
  web:
    image: redpandafinder
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./js:/usr/share/nginx/html/js
      - ./css:/usr/share/nginx/html/css
      - ./images:/usr/share/nginx/html/images
      - ./fragments:/usr/share/nginx/html/fragments