name: deploy-redpandafinder-with-actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build export/redpanda.json
        uses: actions/checkout@v3
        run: |
          pip install -r requirements.txt
          python ./build.py publish
          rm .gitignore
  publish:
    needs: build
    steps: 
      - name: Publish artifact for github pages
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          name: github-pages
          path: ${{ github.workspace }}
          retention-days: 1
  deploy:
    needs: publish
    permissions: 
      pages: write
      id-token: write
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy github pages
        uses: actions/deploy-pages@v1.2.3
        with:
          timeout: 600000
          error_count: 10
          artifact_name: github-pages
